### ISSUE TITLE
Daktronics Hockey Powerplay syncing

### ISSUE THREAD

**Issue by robere2** [rpitv/glimpse-graphics#8]
Powerplay input still needs to be done manually through the messages window. This is not always a simple task and needs to be syncable as soon as possible.

Extra thought needs to go into:
- How this will be done with the current messages system.
- How these data packets behave in other sports which may have penalty timers but don't have power plays.

**Comment by wub2003** [comment]
Resolved https://github.com/rpitv/glimpse-graphics/tree/pp-and-shots-sync
